// section_id_prefix: apif
= API First

API-First ist ein Vorgehen im Rahmen der API-Entwicklung, bei dem die Spezifikation einer API im Zentraum steht mit dem Ziel, die Dienste eines Services transparent zu machen und die Nutzung des Services über seine API von dessen technischer Implementierung zu entkoppeln.

Im Folgenden werde ich den Grundgedanken erklären, welche Vorteile und Nachteile ein API-First Ansatz bietet, sowie auf übliche Missverständnisse dieses Ansatzes eingehen.
Die hier aufgeführten Punkte können als Argumentationshilfe genutzt werden, wenn in einer Organisation das Vorgehen bei der API-Entwicklung diskutiert wird.


== Was bedeutet API First?

:hide-title: 1

include::partial$def-api-first.adoc[]

:hide-title!:

== Grundgedanken

* Vertrag, der verbindlich ist
* Zentrale Spezifikation, die geteilt werden kann
* Kommunikation über Spezifikaiton
* API ist First Class Citizen


== Vorteile


// - Entkopplung, interna werden von der Schnittstelle abgetrennt
// - Bessere Interoperabilität und Integration

=== Systeme werden komponierbar

Eine API Spezifikation senkt den Aufwand und die Hürde für die Entwicklung neuer Prozesse, für die mehrere Systeme integriert werden sollen.
Für eine Integration eines Systems ist lediglich die Kenntnis der API notwendig, die alle  möglichen Operationen des Systems mit den jeweils benötigten Eingabedaten und möglichen Ergebnissen beschreibt.
Für eine Integration eines Systems ist daher nur die Implementierung eines Clients für die API des jeweiligen Systems notwendig.

=== Formale Validierung möglich

Eine formale Spezifikation einer API mittels einer für den Typ der API vorgesehenen Beschreibungssprache, beispielsweise mittels der OpenAPI Specification für REST-APIs oder der ganz alten Web Services Description Language (WDSL) für SOAP Services, resultiert immer in einer maschinenlesbaren Beschreibung der API.

Deren Existenz erlaubt es, die Frage zu stellen und mittels Toolings zu beantworten: "*Ist die Spezifikation syntaktisch korrekt?*"

Auch die darüber hinausgehende Frage "*Entspricht die API unseren eigenen Standards?*" kann so beantwortet und die Einhaltung sichergestellt werden.


=== Toolunterstützung

Durch den API-First-Ansatz steht für eine API immer eine formale Beschreibung zur Verfügung, die von externen und eigenen Tools verarbeitet werden kann.
Übliche Anwendungsfälle sind hier die automatische Generierung von Client- und Server-Implementierung, die Konvertierung der Spezifikation in unterschiedliche Ausgabeformate im Rahmen der Verteilung von Dokumentation und die Validierung der Spezifikation selber.


=== Die Spezifikation ist die Dokumentation

Bei API-First steht die Spezifikation im Vordergrund als zentrales Artefakt, welches die Grundlage für jede Implementierung, egal ob als API-Provider oder API-Client, dient.
Da die Spezifikation alle Aspekte in Bezug auf Operationen, und damit das Verhalten der API, und die für die Operationen mit der Operation verbundenen Daten beschreibt, ist eine nachträgliche Dokumentation der API nicht notwendig.
*Eine API-Spezifikation fungiert auch immer gleichzeitig als Dokumentation einer API.*

// - Nachhaltig
// - Aufwand für Reverse Engineering sinkt
// - Effizienz steigt, da Teams parallel die API implenentieren können

== Nachteile

// - Die Implementierung muss sich an Spezifikation halten

== Übliche Missverständnisse

// - Design muss nicht von Implementierung entkoppelt werden
// - Das ist nicht agil
// - Das ist zu aufwendig

== Best Practices



// - Klarheit über Datenmodel
// - Prototypische Implementierung parallel zur Spezifikation
// - Formale Validierung!


== Fazit


// todo Später verlinken mit der Seite zum Ansatz Code First
// todo Später verlinken mit der Seite zum Vergleich zwischen Code First und API First
// todo Später verlinken mit der Seite zur Klassifikation von APIs

