// section_id_prefix: qcaa_
= Qualitätskriterien für eine API

Auf dieser Seite stelle ich einen leichtgewichtigen Satz von Qualitätskriterien für APIs vor.
Die hier vorgestellten Kriterien sind hilfreich, wenn es um die Beurteilung der Qualität und des Reifegrades einer API geht.
Zudem kann mithilfe dieser Kriterien eine bessere Qualität und vergleichbare Ergebnisse bei dem Review von APIs sichergestellt werden.

== Qualitätskriterien bewusst auswählen

Nicht jedes einzelne der hier aufgeführten Qualitätskriterien ist für jede API notwendig.
Vielmehr muss für jede API im Einzelfall entschieden werden, welches Qualitätskriterium einen Mehrwert bietet und ob diese im konkreten Falle einen Mehrwert bietet, der den Aufwand für dessen Erreichung gerechtfertigt ist.
Jedoch sollte diese Entscheidung bewußt getroffen werden und nicht zufällig erfolgen.

[#qcaa_]
== Existenz einer API-Beschreibung

Für die API existiert eine API-Beschreibung, entweder als rein textuelle Beschreibung oder als formale Spezifikation in einem für die Art der API entwickelten Standard.

[#qcaa_]
== Existenz einer formalen API-Beschreibung

Es existiert eine formale API-Spezifikation in einem für die API entwickelten Standard und kann mit entsprechendem Tooling verarbeitet werden.
Dies ist eine relevante Grundlage für jegwede Art der Automatisierung, beginnen von Validierung bis hin zur Code-Generierung.

[#qcaa_]
== Syntaktische Korrektheit der API-Beschreibung

[#qcaa_]
== Beschreibung aller Operationen

Die API-Spezifikation beschreibt alle möglichen Operationen der API.

Für die Erreichung dieses Kriteriums muss die API-Spezifikation folgende Aspekte abdecken:

* Alle Operationen sind aufgeführt
* Jede Operation ist hinsichtlich ihres Verhaltens beschrieben

// [#qcaa_]
// ==

// [#qcaa_]
// ==

// [#qcaa_]
// ==

// [#qcaa_]
== Eigentümer der API ist ersichtlich

Aus der API-Spezifikation ist ersichtlich, wer der Eigentümer der API ist und an wen sich Betreiber von API-Clients im Falle von Problemen und Anforderungen wenden können.

Im Einzelnen sollte aus der API-Spezifikation heraus ersichtlich sein:

* Wer ist fachlich für die API verantwortlich
* Wer ist für den technischen Betrieb der API verantwortlich
* Wo ist die API-Spezifikation kanonisch hinterlegt
* Wie können die für die API-Verantworlichen erreicht werden

[#qcaa_visibility]
== Sichtbarkeit der API ist beschrieben

Aus der API-Spezifikation heraus können folgende Fragen beantwortet werden:

* Für welchen Benutzerkreis ist API gedacht und freigegeben?
* Welcher Sichtbarkeitsklasse ist die API zuzuordnen?

Siehe hierzu auch xref:classification-of-apis.adoc[]

// - Fehlerverhalten jeder Operation ist beschrieben
// - Verwendete Datenstrukturen sind beschrieben
// - Bedeutung der Datenstrutkuren und der einzelnen Felder sind beschrieben
// - Verwendete Begriffe sind einheitlich im Kontext der Aufgabe und oder der Organisation
